### ISSUE TITLE
Add `link-block` object

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy#77]
Allow to transform an anchor tag into a block:

``` sass
.link-block { display: block; color: inherit;
  &:hover { text-decoration: none; }
}
```

**Comment by Gregcop1** [comment]
In the styleguide we let a blank line before `&:hover`

Dunnno if `text-decoration` or `color` are related to a `link-block`

**Comment by Plou** [comment]
I remove text-decoration and color, because this class is meant to be use as below:

``` html
<a href="/" class="whatever link-block">
  <h1 class="whatever-title">Title</h1>
  <img src="whatever.png" class="whatever-thumbnail" alt="">
  <p class="whatever-description">lorem</p> 
</a>
```

**Comment by Gregcop1** [comment]
ok

**Comment by Plou** [comment]
I'm thinking about a documentation to list available objects and helpers. A thing to add to the memo

**Comment by Gregcop1** [comment]
A sublime text plugin ;) <3

**Comment by Plou** [comment]
I heard about one, something like "auto-something", "completion" I think.

**Comment by Gregcop1** [comment]
ST add all available helpers of your project ?

**Comment by Plou** [comment]
I remember a plugin which add all classes found in the project to autocomplete, or perhaps it was only in opened files.
