### ISSUE TITLE
Add `nostyles` objects

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy#78]
``` sass
.nostyle {
  margin: 0; padding: 0;
}

.nostyle-list  { margin: 0; padding: 0; list-style: none;
  > li { margin: 0; padding: 0;
    &::before { display: none; }
  }
}
```

**Comment by Gregcop1** [comment]
If you have a helper `noStyle` you can use it in :
- `.noStyle`
- `.noStyle-list`
- `.noStyle-list > li`

Why the `before` ?

**Comment by Plou** [comment]
The snippet comes from a project where the list bullets are added using the `::before`

**Comment by Gregcop1** [comment]
ok. So we have to ask ourself if this kind of habits is common in dummy project or not

**Comment by Plou** [comment]
I'm not sure it is a good idea anymore, cause it will move some style logic back into the html.

`.function { margin:0; padding: 0 }` is way better than `<ul class="function nostyle-list">...</ul>`

So we don't have to alter the html in order to update the design.

I label it invalid until anybody say otherwise.
